apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    service: api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-feed
  template:
    metadata:
      labels:
        service: api-feed
    spec:
      containers:
      - name: api-feed
        image: dutn1/udagram-api-feed:v2
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"                  
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
        ports:
          - containerPort: 8080